#### DB Diagram
https://github.com/near/near-indexer-for-explorer/blob/master/docs/near-indexer-for-explorer-db.png

In [1]:
import psycopg2  # pip3 install psycopg2
import pandas as pd # pip3 install pandas

In [2]:
# postgres://public_readonly:nearprotocol@35.184.214.98/testnet_explorer
conn = psycopg2.connect(host="35.184.214.98", database="testnet_explorer", user="public_readonly", password="nearprotocol")

In [3]:
query = """
SELECT DISTINCT(action_kind)
FROM action_receipt_actions
LIMIT 10
"""

df = pd.read_sql_query(query, conn)
df.head(10)

       action_kind
0   CREATE_ACCOUNT
1  DEPLOY_CONTRACT
2    FUNCTION_CALL
3         TRANSFER
4            STAKE
5          ADD_KEY
6       DELETE_KEY
7   DELETE_ACCOUNT

In [4]:
account = "loganbon.testnet"
# account = "evolution4good.testnet"

query_acct = f"""
SELECT *
FROM action_receipt_actions
WHERE receipt_receiver_account_id = '{account}' OR receipt_predecessor_account_id = '{account}'"""

df = pd.read_sql_query(query_acct, conn)
df.head(10)

,receipt_id,index_in_action_receipt,action_kind,args,receipt_predecessor_account_id,receipt_receiver_account_id,receipt_included_in_block_timestamp
0,GBYfvyGJHJu97QTZTkKZj7Z7uN1BQmCMH6dtwABWPaxa,0,CREATE_ACCOUNT,{},testnet,loganbon.testnet,1.642437e+18
1,GBYfvyGJHJu97QTZTkKZj7Z7uN1BQmCMH6dtwABWPaxa,1,TRANSFER,{'deposit': '200000001000000000000000000'},testnet,loganbon.testnet,1.642437e+18
2,GBYfvyGJHJu97QTZTkKZj7Z7uN1BQmCMH6dtwABWPaxa,2,ADD_KEY,"{'access_key': {'nonce': 0, 'permission': {'pe...",testnet,loganbon.testnet,1.642437e+18
3,2aKqKDqUDLYA7xjyJFDrycieCcfRXy1AmDmCWbWQEt9M,0,ADD_KEY,"{'access_key': {'nonce': 0, 'permission': {'pe...",loganbon.testnet,loganbon.testnet,1.642437e+18
4,5ptHnBEcxsWXRbVBkKtdpL7PBiaVKAXEJzGV6UFmSsPv,0,TRANSFER,{'deposit': '199999247156894490200000000'},system,loganbon.testnet,1.642554e+18
5,A9rH4TmEexody8cqHRgFjJQgy8cPv5tG4F61DLXgKXvG,0,TRANSFER,{'deposit': '669547687500000000'},system,loganbon.testnet,1.642610e+18
6,DamH6DiGmatovpn2jM1QEcPF1JASpdYWpr5diCfhtMzG,0,TRANSFER,{'deposit': '20000000000000000000000000'},loganbon.testnet,evolution4good.testnet,1.642610e+18
7,FPJgEN9YccMfUC8BdonJ6znazXYntPk3y7b8hGEZuJ5N,0,TRANSFER,{'deposit': '50000000000000000000000000'},evolution4good.testnet,loganbon.testnet,1.642611e+18

In [5]:
def calculate_amount(amount):
    # NEAR token has 24 decimals
    return float(int(amount)/(10**24))

In [6]:
calculate_amount(50000000000000000000000000)

50.0